spring:
  application:
    name: payflowguard

  datasource:
    url: jdbc:postgresql://localhost:5432/payflowguard
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  webhooks:
    payment-status-url: "https://webhook.site/7ed95e6a-71d1-4bb3-b799-726d9a003ba2"