spring:
  application:
    name: payflowguard

  datasource:
    url: jdbc:postgresql://localhost:5432/payflowguard
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  webhooks:
    payment-status-url: "https://webhook.site/8c5a5747-3f6a-4e90-8876-3d936a7c7f3e"