spring:
  application:
    name: payflowguard

  datasource:
    url: jdbc:postgresql://localhost:5432/payflowguard
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  security:
    jwt:
      secret: "${JWT_SECRET}"

  webhooks:
    payment-status-url: "${PAYFLOW_WEBHOOK_URL:http://127.0.0.1:9999/webhook}"
